- packages/clients/meldemichel/src/mapConfigurations.ts
Add staticAttributions linking to the copyright information and sbom.
- `npm run meldemichel:dev` and `npm run meldemichel:build && npm run meldemichel:build:example`
#6
> Add staticAttributions linking to the copyright information

- packages/lib/passesBoundaryCheck/index.ts
- packages/lib/passesBoundaryCheck/package.json
- packages/types/custom/CHANGELOG.md
- packages/types/custom/core.ts
A common type for plugins bound by layer boundaries has been introduced.
Running pipeline is sufficient, no direct effects on code.
> deduplicate bound layer types

- packages/plugins/IconMenu/CHANGELOG.md
- packages/plugins/IconMenu/src/components/IconMenu.vue
- Replaced hack with absolute positioning.
- Fixed bug that appeared when Zoom was sorted prior to Attributions, but decided to not render itself due to tiny client window.
- Remove spacing on IconMenu's ul that seems to have leaked in unnoticed.
Run arbitrary clients in arbitrary environments to check if something is broken. Most notable change should occur in Meldemichel example clients for `'SINGLE'` mode, where the attributions were previously displayed above the map.
> fix icon menu content placement

- packages/plugins/AddressSearch/src/store/getters.ts
- packages/plugins/Attributions/src/store/index.ts
- packages/plugins/Draw/src/store/index.ts
- packages/plugins/Fullscreen/src/store/index.ts
- packages/plugins/GeoLocation/src/store/getters.ts
- packages/plugins/Gfi/src/store/getters.ts
- packages/plugins/IconMenu/src/store/index.ts
- packages/plugins/Pins/src/store/index.ts
- packages/plugins/Zoom/src/store/index.ts
The parameter `configuration` of the `core` store is always defined so optional chaining is not necessary.
If the pipeline succeeds, we are good to go
\- / -
> Fix: Type access to core configuration

- packages/plugins/Scale/CHANGELOG.md
- packages/plugins/Scale/src/components/Scale.vue
There were linebreaks here. They're gone now.
Test Meldemichel clients on local GitHub pages with mobile device, if need be.
> fix linebreak on ratio scale on narrow devices

- packages/plugins/Attributions/CHANGELOG.md
- packages/plugins/Attributions/src/language.ts
- packages/plugins/Attributions/src/utils/lib.ts
- packages/plugins/Attributions/tests/attributions.spec.ts
As required by the EUPL license, a link as well as the license are always linked to when the attributions plugin is used.
Start any client and open the attributions. When using `snowbox`, the locale switch can be tested with #27 in mind.
> Add link to repository and license as required by EUPL v1.2

- packages/core/src/components/MapContainer.vue
Whenever the user focused on any element that was not the map, the map overlay was still being shown. This was especially annoying when scrolling the legend.
- `npm run snowbox`
- Open legend
- Scroll
- The overlay is not visible
One can now scroll on any part of the page other than the map and the overlay is only shown, once the cursor is actually on the `div` of the map.
> Fix map overlay being visible on desktop if map is not in focus

- packages/plugins/AddressSearch/src/components/Results.vue
Prior implementation has been replaced with DOM navigation that is easier to reason about.
Check in DISH and Meldemichel. Relevant search strings to DISH are "Rathaus", "Rathausm", and "2-20/Rathausstraße".
Resolves #26
> refactor address search keyboard navigation

- packages/core/CHANGELOG.md
- packages/core/README.md
- packages/plugins/AddressSearch/CHANGELOG.md
- packages/plugins/AddressSearch/README.md
- packages/plugins/Draw/CHANGELOG.md
- packages/plugins/Draw/README.md
- packages/plugins/Export/CHANGELOG.md
- packages/plugins/Export/README.md
- packages/plugins/Fullscreen/CHANGELOG.md
- packages/plugins/Fullscreen/README.md
- packages/plugins/GeoLocation/CHANGELOG.md
- packages/plugins/GeoLocation/README.md
- packages/plugins/Gfi/CHANGELOG.md
- packages/plugins/Gfi/README.md
- packages/plugins/LoadingIndicator/CHANGELOG.md
- packages/plugins/LoadingIndicator/README.md
- packages/plugins/Pins/CHANGELOG.md
- packages/plugins/Pins/README.md
- packages/plugins/Zoom/CHANGELOG.md
- packages/plugins/Zoom/README.md
There has been a mixup about state and getters in the plugin documentation. Since state and getters have to be listened to with deviating methods, a fix was in order.
Resolves: #37
> fix listening documentation

- packages/clients/meldemichel/API.md
- packages/clients/meldemichel/CHANGELOG.md
- packages/clients/meldemichel/example/index.html
- packages/clients/meldemichel/src/html/index.html
- Update Meldemichel COMPLETE mode documentation
- Update Meldemichel CHANGELOG
- Update example files to use correct services / show correct texts
`npm run meldemichel:build && npm run buildPages && npx http-server pages_output -o index.html` to open the page locally that's later published to our GitHub Page.
> chore: update documentation

- packages/clients/afm/CHANGELOG.md
- packages/clients/afm/src/polar-client.ts
- packages/clients/dish/CHANGELOG.md
- packages/clients/dish/src/addPlugins.ts
- packages/clients/meldemichel/CHANGELOG.md
- packages/clients/meldemichel/src/utils/createMenus.ts
- packages/clients/snowbox/src/addPlugins.ts
After some feedback it became clear, that the previously used atlas icon needed to be replaced with a different icon.  
The decision fell on `layer-group` as it most closely resembles the usage one sees in e.g. Google Maps.
As all clients have been updated, all clients should be run and checked.
> Update icons of layerChooser to be clearer for the content behind it

- packages/clients/dish/src/plugins/Gfi/Content.vue
- packages/clients/meldemichel/src/plugins/Gfi/Feature.vue
- packages/core/CHANGELOG.md
- packages/core/src/components/MapContainer.vue
- packages/core/src/vuePlugins/vuex.ts
- packages/lib/createTestMountParameters/CHANGELOG.md
- packages/lib/createTestMountParameters/index.ts
- packages/plugins/Gfi/src/components/Gfi.vue
- packages/plugins/Gfi/src/store/getInitialState.ts
- packages/plugins/Gfi/src/types.ts
- packages/types/custom/CHANGELOG.md
- packages/types/custom/core.ts
Resolves the issue of the switch buttons only appearing on the second click on a clustered feature.
Both clients should be tested on narrow and wide devices. Below instructions are for narrow devices.
- Meldemichel:
- Search `Annenstraße` and choose the street
- Zoom to maxZoom
- Click on the remaining cluster
- The switch buttons should be visible on first click
- Click another feature, that is not a cluster
- The switch buttons should be hidden
- DISH:
- Click anywhere in the map where you suspect a feature
- The export button should be shown in the top-left 
Resolves #55
> Refactor actionButton handling to fix gfi switch buttons issue

- packages/plugins/Gfi/CHANGELOG.md
- packages/plugins/Gfi/src/components/List.vue
The focused feature is now highlighted with a solid border, the hovered with a dashed border, and map/neighbour focusing is indicated with a greenish background to the features.
This way, all states of highlighting should be easier to decipher for end users.
Visual check including mixed usage with keyboard and mouse on list and map.
Resolves #67
Resolves #68
> improve focus highlighting on WFS List

- packages/plugins/Attributions/CHANGELOG.md
- packages/plugins/Attributions/src/store/index.ts
See commit history.
Check whether scenario in issue now works. (shortcut: `npm run afm:dev`, open Attributions, zoom out)
Resolves #5
> fix update attribution on leaving layer resolution

- packages/plugins/Fullscreen/CHANGELOG.md
- packages/plugins/Fullscreen/src/components/Fullscreen.vue
An aria label was missing. It's there now.
Check with NVDA, if need be.
> add missing aria label

- arcana.md
- package.json
- packages/clients/meldemichel/CHANGELOG.md
- scripts/overrideMasterportalapi.js
See added file's `scripts/overrideMasterportalapi.js` for details. While this is a global change, I decided to document it in the Meldemichel, since it's the only client using this right now *and* the change results in a new Meldemichel beta release.
To save you the search, https://bitbucket.org/geowerkstatt-hamburg/masterportalapi/src/master/src/searchAddress/searchGazetteer.js is the file's current state. In case of masterportalapi update, we can do this properly.
Install (to trigger postinstall) and run the `client:meldemichel:dev`. Should the changes not arrive, it may be required to add `--force` to the vite command in the root package.json once to avoid vite's cache, which plausibly does not detect manual module changes.
An interesting search is for "Roonstraße". This produced …
> remove wildcard on street search

- packages/plugins/AddressSearch/CHANGELOG.md
- packages/plugins/AddressSearch/src/components/Results.vue
Fixes the keyboard navigation not working on browsers other than Firefox as [originalTarget](https://developer.mozilla.org/en-US/docs/Web/API/Event/originalTarget) is non-standard.
Check meldemichel and dish if the keyboard navigation works in all kinds of browsers.
> Fix keyboard navigation of address search

- packages/clients/afm/API.md
- packages/clients/afm/example/index.html
- packages/clients/afm/example/prod-example.html
- packages/clients/dish/src/index.html
- packages/clients/generic/API.md
- packages/clients/meldemichel/API.md
- packages/clients/meldemichel/src/html/index.html
- packages/clients/meldemichel/src/index.html
- packages/clients/snowbox/src/index.html
Add advisory to use noscript tag in POLAR's render div, should no other place on the page take care of this. No matter now noscript-compatible a page is, we are not.
Test whether `<noscript>` tag (added where possible) interfered with workflow.
I've skipped changelogs since no substantial changes have been made.
Resolves: #104
> add noscript advisory

- packages/types/custom/CHANGELOG.md
- packages/types/custom/core.ts
SearchType was previously hard-wired to pre-defined search types. However, since any client may add custom search methods, any string can be allowed as search type.
This allows `string` as search type for clients to use their own defined search methods without errors messages.
> fix type to allow custom strings for custom methods

- packages/plugins/AddressSearch/CHANGELOG.md
- packages/plugins/AddressSearch/src/components/Results.vue
Feature titles may now optionally hold locale keys. If the title is not found within the locales, it will be shown as-is.
No test environment given, will be used in the TextLocator.
> add optional i18n for feature titles

- packages/plugins/Draw/src/store/index.ts
The vector source can now be fetched via getter, circumventing the previous necessity to dig it out from the map. The CHANGELOG was intentionally left unchanged as this is internal API only.
> add vector source getter to draw plugin

- packages/clients/meldemichel/CHANGELOG.md
- packages/clients/meldemichel/src/addPlugins.ts
- packages/clients/meldemichel/src/mapConfigurations.ts
It was requested that a feature can be reverse geocoded and the address search can be used programmatically in mode `SINGLE`.  
An addition to the API.md was redundant, as the programmatic usage has already been described in the README of `@polar/plugin-address-search`.
- Add the `mapInstance` to the `window` object in `packages/clients/meldemichel/example/single.html`.
- Use the following code snippet to trigger the search.
```js
window.$mapInstance.$store.dispatch('plugin/addressSearch/search', {
input: 'Spitalerstraße 12',
autoselect: 'first'
})
```
A pin should be set to `Spitalerstraße 12` and the following fields should have a value
- `vendor_maps_address_str`
- `vendor_maps_address_hnr`
- `vendor_maps_address_plz`
- `vendor_maps_distance_to`
> Add AddressSearch and ReverseGeocoder to 'SINGLE' mode of meldemichel

- packages/plugins/Pins/CHANGELOG.md
- packages/plugins/Pins/src/store/getters.ts
- packages/plugins/Pins/src/store/index.ts
- packages/plugins/Pins/src/store/state.ts
- packages/plugins/Pins/src/types.ts
Oddly, the map would pan with the marker drag after switching to fullscreen mode, effectively rendering the marker almost immovable. This has been resolved by updating the Translate interaction on map size changes.
Since the file was of >300 lines size and the setup method was too long, I've refactored it while touching it. The actual fix is merely these lines:
```
// without update, map will pan during drag
this.watch(
() => rootGetters.hasSmallWidth || rootGetters.hasSmallHeight,
() => dispatch('updateMarkerDraggability')
)
```
`npm run meldemichel:dev` with [index.zip](https://github.com/Dataport/polar/files/14601162/index.zip) used instead of the usual `index.html` in `meldemichel/src` to test the affected mode. Also testing the Pins plugin in other situations to make sure no unwanted …
> fix marker draggability after map size change

- pages/examples/address.html
- pages/examples/draw.html
- pages/examples/gfi.html
- pages/examples/layer.html
- pages/examples/locales.html
- pages/examples/orientation.html
- pages/examples/render.js
- pages/index.html
- pages/polar.css
Change all `<aside>`-elements to `<div>`-elements with the same style as prior `<aside>`-elements, as the main content is currently displayed in those elements.  
Adjusted the box-shadow on hover to be more visible.
`npm run pages:build` & `npm run pages:build:serve`
> Change all asides to divs as they hold main content

- packages/plugins/IconMenu/CHANGELOG.md
- packages/plugins/IconMenu/src/components/IconMenu.vue
- packages/plugins/IconMenu/src/store/index.ts
- packages/plugins/IconMenu/src/types.ts
See the commit for more information.
- `npm run meldemichel:dev`
- As configured, the `layerChooser` should be open on start
> Fix issue of initiallyOpen in @polar/plugin-icon-menu not working

- packages/clients/snowbox/src/index.html
- packages/plugins/Export/CHANGELOG.md
- packages/plugins/Export/README.md
- packages/plugins/Export/src/store/actions.ts
The export plugin incorrectly showed an JPG when it was configured for a PDF export with download:false.
This behaviour will be fixed with this pull request. 
Therefore the generic client will use an embend element to display the PDF, which is also capable to show images.
- configure the generic client to show PDF: 
`  export: {
showPng: false,
showJpg: false,
showPdf: true,
},`
- run the snowbox
`npm run snowbox`
- click the "Export as .pdf file" button
> Fix: PDF export with download:false

- packages/clients/meldemichel/CHANGELOG.md
- packages/clients/meldemichel/src/mapConfigurations.ts
As requested by the customer, `@polar/client-meldemichel` no longer focuses on the first result after a successful search.
`npm run meldemichel:dev`
> Change meldemichel to no longer focus on the first result

- packages/plugins/Filter/CHANGELOG.md
- packages/plugins/Filter/src/utils/updateFeatureVisibility.ts
- Selecting a single day filtered features in a way that selected only the day after the day selected.
- Selecting a date range added another day at the end.
These issues have been resolved.
This fix can easily be tested in `npm run meldemichel:dev` since features denote their date in GFI and the filter is configured.
> fix bugs in time frame filter

- packages/plugins/GeoLocation/CHANGELOG.md
- packages/plugins/GeoLocation/src/store/actions.ts
Fix the GeoLocation plugin that accessed `navigator.permissions.query` without checking whether it's supported prior, resulting in a failure of the map initialization on Safari versions below 16 and some other browsers.
This can be tested in the Meldemichel on a device with Safari<16. Since the map will not request access to the geolocation feature initially, it will simply proceed to try and fetch the geolocation; this triggers the usual request and will lead to an error toast.
> fix GeoLocation failing map init on Safari<16

- pages/documentation.html
On https://dataport.github.io/polar/documentation.html the link to the plugin gallery was incorrect. This has been fixed.
Check whether the new link is correct.
> Fix incorrect link on documentation page linking to plugin gallery

- package-lock.json
- packages/clients/textLocator/src/utils/literatureByToponym.ts
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/lib/tooltip/package.json
- packages/plugins/Scale/package.json
All @polar/core dependencies have been updated where updates, where compatible with our Vue@2 setup.
No breaking change affected us, and most dependencies were implicitly already installed in the version noted now. Clients can be arbitrarily tested for i18n still working, which was the only breaking change.
> update @polar/core dependencies

- package.json
- packages/clients/dish/src/utils/search.ts
- packages/clients/generic/src/polar-client.ts
- packages/clients/meldemichel/src/addPlugins.ts
- packages/clients/meldemichel/src/store/module.ts
- packages/clients/meldemichel/src/utils/createMenus.ts
- packages/types/custom/core.ts
- tsconfig.ci.json
*looks at ts client check setup*
I can fix it.
Pipeline should now run through and tsc also checks clients. I've fixed the setup in that I added (mostly unnecessarily) default configuration properties (that will still throw errors in the plugins if not overridden, so no harm done here) and adjusted some types. I've also entertained `any` to resolve some of the problems, where both `unknown` and `never` would result in errors in varying positions. While not quite ideal, this is imo sufficient by the 20-80 rule.
The biggest gain here is that we've now enabled type checking for clients so that we can stop preventable issues from sneaking in.
> fix ts client check

- packages/clients/generic/CHANGELOG.md
- packages/clients/generic/src/polar-client.ts
- pages/examples/render.js
As the title says, `@polar/client-generic` now additionally exposes `createMap` to be able to use it directly.
`npm run pages:build && npm run pages:build:serve`. This should then also work in the pipeline.
> Additionally expose createMap for @polar/client-generic

- packages/core/CHANGELOG.md
- packages/core/src/components/MapContainer.vue
- packages/core/src/language/locales/de.ts
- packages/core/src/language/locales/en.ts
On macOS, the Command-Key is being used instead of Ctrl as a modifier for zooming.
This change now fixes that, so the Overlay is now being displayed on macOS devices.
Run e.g. `snowbox` and take a look, if it still works as intended for Windows devices.
> Adjust overlay mechanic for macOS devices

- packages/core/src/vuePlugins/vuex.ts
The client now warns upon finding components that are indicated to be visible by the `displayComponent` flag, but lack a `layoutTag`.
You may intentionally break any configuration by removing the layout tag to see the warning.
> add configuration error warning

- packages/core/CHANGELOG.md
- packages/core/src/utils/createMap/pullVuetifyStyleToShadow.ts
Since tooltips are technically a neighbour of the #app, the correct font styles missed the the target.
Check client tooltips. You can e.g. view the difference in DISH.
> fix tooltip font family

- packages/clients/snowbox/src/mapConfiguration.ts
Change order of layers so that the pins dont get overlapped by other layers.
`npm run snowbox`
*No functional changes*
None
> Change order of layers to fix overlapping layers

- packages/plugins/Gfi/CHANGELOG.md
- packages/plugins/Gfi/src/types.ts
- packages/plugins/Gfi/src/utils/requestGfi.ts
If a WMS-Layer had `singleTile` set to `true`, gfi requests were not possible as the `if`-statement only checked for `TileLayer` which is not the case for single-tiled-WMS-layers.
- Configure the Layer with the id `367` in `@polar/client-snowbox` for general usage and gfi
- `npm run snowbox`
- Clicking in the map should yield a result.
- ~~[ ] Screenreader functionality has been manually tested with NVDA~~
- ~~[ ] Chrome Lighthouse~~
- ~~[ ] Firefox Accessibility~~
None
> Allow layers that have singleTile: true set to be used for gfi requests

- packages/clients/diplan/example/config.js
- packages/clients/diplan/example/services.js
Configured an OAF layer as test for XTrasse data.
https://xtrasse.ldproxy.develop.diplanung.de/xtrasse_PFS_gas/collections/bst_gasleitung/items
Run `npm run diplan:dev` and check the environment near Wilhelmshaven for line geometries when the newly configured OAF layer is turned on.
> add xtrasse to diplan client

- packages/core/CHANGELOG.md
- packages/core/README.md
- packages/core/src/components/MapContainer.vue
- packages/plugins/Draw/CHANGELOG.md
- packages/plugins/Draw/src/store/createInteractions/createModifyInteractions.ts
- packages/plugins/Draw/src/store/createInteractions/createTranslateInteractions.ts
Previously, when performing drag-like operation in the Draw plugin, a tooltip would appear on mobile devices, indicating that two fingers could be used to pan the map (whilst e.h. during Translate, a polygon was moved in the background).
This issue has been resolved by introducing a new flag and flag documentation mode. Since we use this at times, this will come in handy for future extension when refactoring such flags to more abstract ones, AND they become reusable for new plugins requiring samey interactions.
Run the snowbox and check the behaviour on a mobile and desktop device for consistency.
Resolves: #227
> remove pan tooltip during drag interaction

- pages/documentation.html
Link to no-existing Badegewässer Client Docs has been deleted because.
- [x ] Changelogs are maintained - **no changelog entry necessary for this**
> delete link to bgw-docs

- packages/clients/dish/src/services.ts
The legend display for all background layers despite basemap has been deactivated. This is a reset to the original configuration due to customer wishes.
Start the DISH client in mode `extern` and check the legend display.
> ignore legends for some background layers

- packages/clients/diplan/example/dev/index.html
- packages/clients/diplan/example/dev/setup.js
- packages/clients/diplan/src/store/geoEditing/duplicatePolygons.ts
The "Duplicate polygon" button is now a broader "Duplicate geometry" button. It does what is says and shows its availability to do so with a "copy" cursor.
Blocks on https://github.com/Dataport/polar/pull/263
`npm run diplan:dev`, draw some geometries and clone them.
> implement geometry cloning

- package-lock.json
- packages/clients/diplan/package.json
Modeled DiPlan client without the peer dependencies since the leading system does not use `--legacy-peer-deps` and versions brought in with this installation would possibly stay in conflict with other installations there. Since POLAR comes pre-bundled, it's pointless for them to know anyway. The packages are not peer from their point of view.
Not much. Might check whether it still works after reinstall.
> remove peer dependencies from diplan

- packages/clients/diplan/example/polar-ui/index.html
- packages/clients/diplan/example/polar-ui/setup.js
- packages/clients/diplan/src/store/geoEditing/cutPolygons/index.ts
- packages/clients/diplan/src/store/geoEditing/duplicatePolygons.ts
- packages/clients/diplan/src/store/geoEditing/mergePolygons.ts
- packages/plugins/Draw/src/store/createInteractions/createLassoInteractions.ts
The methods cutPolygon/mergePolygon/duplicatePolygon are no longer turned off after the first `drawend` of the Draw method. Instead, they now work until intentionally disabled.
The `/polar-ui` example has been extended to showcase these functions and allows turning them off manually.
Check `/polar-ui` example in build mode.
> disable automatic full interaction end on first end

- packages/core/CHANGELOG.md
- packages/core/src/components/MapContainer.vue
- packages/core/src/utils/mapZoomOffset.ts
- packages/plugins/LayerChooser/CHANGELOG.md
- packages/plugins/LayerChooser/README.md
`minZoom` was wrong by one zoom level due to a change in parameter forwarding in the `@masterportal/masterportalapi`. This has been resolved by mapping the value for the masterportalapi appropriately. No changes regarding the usage in POLAR have been made, the parameter is still meant inclusively on our end. This is to avoid the breaking changes in all configurations using it.
Run e.g. `diplan:dev` to see the change in effect.
> fix minZoom for layers to work from minZoom on

- packages/core/src/components/MapContainer.vue
- packages/core/src/vuePlugins/actions/addInterceptor.ts
The store was not completely initialized so the regular expression was not yet added to the store. This PR fixes that by adding it as a parameter to the aciton.
`npm run diplan:dev` & use the patch I provided you. The layer should load again
> Fix issue of addInterceptor not having access yet to the regex

- packages/plugins/Draw/CHANGELOG.md
- packages/plugins/Draw/src/store/createInteractions/getSnaps.ts
The `snapTo` configuration has been changed to stop snapping to the layers while they're invisible.
E.g. `diplan:dev` can be used to verify that interactions no longer snap to parcels while they're invisible.
> prevent snapping to invisible layers

- packages/clients/diplan/src/store/geoEditing/duplicatePolygons.ts
Previously, duplicated geometries would sometimes have the OL default select style in build mode that did not appear in dev mode. This has been resolved and now works as expected in both modes.
Validate in build mode of diplan client.
> fix duplicate polygon style

- packages/clients/diplan/example/diplan-ui-one/config.js
- packages/clients/diplan/example/diplan-ui-two/config.js
- packages/clients/diplan/src/config.js
- packages/clients/diplan/src/locales.ts
- packages/clients/diplan/src/plugins/LayerChooser/LayerChooser.vue
- packages/clients/diplan/src/plugins/LayerChooser/LayerWrapper.vue
Add an additional layer type `xplan` for the LayerChooser in `@polar/client-diplan`.
`npm run diplan:dev` and see the new category in the LayerChooser
> Add a layer group for xplan layers in @polar/client-diplan

- packages/clients/diplan/example/diplan-ui-one/index.html
- packages/clients/diplan/example/diplan-ui-one/setup.js
- packages/clients/diplan/example/diplan-ui-two/index.html
- packages/clients/diplan/example/polar-ui/index.html
- packages/clients/diplan/example/polar-ui/setup.js
- packages/clients/diplan/src/index.html
- packages/clients/diplan/src/setup.js
The examples were inconsistent/dysfunct regarding the screenshot button. This has been smoothened. While at it, placeholder rows have been removed as per Curly's Extended Law. ("Do two things at most.")
See dev mode and diplan-ui-one examples. In all others, the feature has been hidden.
> fix diplan export example

- packages/plugins/Draw/CHANGELOG.md
- packages/plugins/Draw/src/utils/createDrawStyle.ts
Fix measurement calculation.
Visible in e.g. Snowbox. Außenalster has about a km width at its largest, but you may use other things of known size.
> fix measurement calculation

- packages/plugins/IconMenu/CHANGELOG.md
- packages/plugins/IconMenu/src/store/index.ts
- packages/plugins/IconMenu/tests/store.spec.ts
Fix issue of an opened icon menu plugin disappearing when resizing or changing the orientation of a mobile device.
`npm run meldemichel:dev` and resize / change orientation for mobile simulation when a plugin is open. It should now stay open.
- ~~[ ] Functionality has been tested with 200% screen zoom~~
- ~~[ ] Screenreader functionality has been manually tested with NVDA~~
> Remove redundant if-statement breaking the open menu on resize

- packages/clients/dish/src/index.html
The mode 'extern' is now set as default in the index.html.
-
> dish client: set mode to extern

- packages/core/src/utils/createMap/index.ts
A prior refactor broke the defaulting; not all targets also got the default values as a baseline, due to what e.g. the `epsg` value was missing in BKG address search as configured in the bgw client. Now it's made sure that the default values are used everywhere, also if we later add additional default values.
See that e.g. `npm run bgw:dev` has a working BKG address search again.
No changelog entry required since there was no release since the bug appeared and it in itself was merely a refactor.
Was broken in https://github.com/Dataport/polar/pull/297.
> add default values to config in all spots

- packages/clients/snowbox/src/authentication.ts
- packages/clients/snowbox/src/html/index.html
- packages/clients/snowbox/src/index.html
- packages/clients/snowbox/src/polar-client.ts
- packages/clients/snowbox/src/validateForm.ts
Add an example on how to login and save the token to @polar/client-snowbox.
This should subsequently be updated including a service and a keycloak server with which one can showcase the usage of secured services. This should be added in a separate PR once we've got ahold of those things.
`npm run snowbox` and check that you can login with the previously provided credentials. Note that a CORS plugin is required.
Example based on removed example from #311
> Addition of a login example to @polar/client-snowbox

- packages/core/CHANGELOG.md
- packages/core/src/components/MapContainer.vue
A "region" role has been added to the render div.
* Chrome Lighthouse indicated that an `aria-label` on a `div` is insufficient.
* Supposedly JAWS doesn't read that `aria-label` without further ado: https://stackoverflow.com/questions/42681485/div-aria-label-not-being-read-by-jaws
* NVDA didn't care, we can't really tell if it helped except for the Lighthouse warning vanishing (maybe it matters in Safari VoiceOver?)
Run Chrome Lighthouse check.
> add region role to map div

- gettingStarted.md
- packages/clients/bgw/src/polar-client.ts
- packages/clients/dish/src/polar-client.ts
- packages/clients/textLocator/src/polar-client.ts
- packages/core/CHANGELOG.md
- packages/core/README.md
@masterportal/masterportalapi already handles this. It is important to note that it is an async function that can not be awaited when used with a URL. Thus, it becomes required to still call it a second time in such cases.
Run `bgw`, `dish` and `textLocator` and check whether they still run properly.
Note that dish may have some issues loading one feature layer in production mode, but that issue already exists on `main`.
> Remove need to call initializeLayerList for local service registers

- packages/clients/dish/src/mapConfigurations/mapConfigIntern.ts
Simple configuration changes: the gfi of the internal dish client is now yellow again.
- start the dish client in mode `INTERN`
- click on a monument object
- the highlighting should now be outlined yellow instead of blue.
> Dish: apply new gfi highlight

- packages/clients/dish/src/mapConfigurations/layerConfigIntern.ts
Since the intranet services are not available for us, we decided to switch to basemap as default baselayer, at least for the test environment.
- start the dish client with `mode=INTERN` (to see the monument services you have to use the VPN connection, you might also need a browser addon to prevent CORS errors)
- check if the grey basemap is shown in the client
> use basemap as default baselayer

- packages/clients/diplan/CHANGELOG.md
- packages/clients/diplan/example/diplan-ui-one/config.js
- packages/clients/diplan/example/diplan-ui-two/config.js
- packages/clients/diplan/example/services.js
- packages/clients/diplan/src/config.js
- packages/clients/meldemichel/CHANGELOG.md
- packages/clients/meldemichel/src/mapConfigurations.ts
The previous id has been removed from the service register and has been superseded by the one added in this PR.
Run meldemichel and check whether the aerial photo layer can be rendered again.
> Use updated layer id for the aerial photo layer

- package-lock.json
- package.json
Make snowbox work on Windows devices.
`npm run snowbox` should now work on Mac/Linux/Windows with `cross-env` introduced to set variables.
> fix: make snowbox run on windows

- packages/clients/snowbox/src/mapConfiguration.ts
- packages/lib/getFeatures/CHANGELOG.md
- packages/lib/getFeatures/wfs/parse.ts
Some WFS do not return the CRS they respond with as part of the FeatureCollection, but merely as part of their children. In such cases, the first-best find from a child is now assumed to be the return's CRS.
A fitting search for Hamburg has been added as part of the snowbox to test this.
> fix: interpret crs from non-root return
